#!/bin/bash

# Add all knowledge base links from backup
echo "Adding knowledge base links..."

# Array of URLs from the backup
urls=(
    "https://github.com/permissionlesstech/bitchat"
    "https://github.com/cashubtc/xcashu"
    "https://github.com/SovranBitcoin/Sovran"
    "https://github.com/hzrd149/chessnut"
    "https://github.com/permissionlesstech/bitchat-android"
    "https://github.com/ShilohEye/bitchat-terminal"
    "https://github.com/arbadacarbaYK/mcp-chrome"
    "https://github.com/arbadacarbaYK/myLNBitch"
    "https://github.com/arbadacarbaYK/Fuente"
    "https://github.com/lnbits/lnbits/wiki/Tooling-&-Building-with-LNbits"
    "https://github.com/arbadacarbaYK/awesome-nostr/tree/main"
    "https://github.com/arbadacarbaYK/awesome-nostr"
    "https://github.com/d4rp4t/BTCNutServer"
    "https://supertestnet.github.io/nwc_tester/"
    "https://github.com/synonymdev/bitkit"
    "https://github.com/cashubtc/eNuts"
    "https://github.com/getAlby/ZapPlanner"
    "https://github.com/getAlby/mcp"
    "https://cryptodeeptech.ru/private-key-debug/"
    "https://cryptodeeptech.ru/bitcoin-bluetooth-attacks/"
    "https://github.com/conduition/expo-wasm-demo"
    "https://github.com/cashubtc/cdk"
    "https://github.com/cashubtc/cashu.me"
    "https://github.com/cashubtc/cashu-ts"
    "https://github.com/cashubtc/nuts"
    "https://github.com/cashubtc/awesome-cashu"
    "https://github.com/elnosh/gonuts"
    "https://github.com/gandlafbtc/nutstash-wallet"
    "https://github.com/zeugmaster/macadamia"
    "https://github.com/shopstr-eng/shopstr"
    "https://github.com/zeugmaster/CashuSwift"
    "https://github.com/cashubtc/docs.cashu.space"
    "https://github.com/AquaWallet/aqua-wallet"
    "https://github.com/spesmilo/electrum"
    "https://github.com/lightninglabs/lightning-app"
    "https://github.com/hsjoberg/blixt-wallet"
    "https://github.com/getAlby/lightning-browser-extension"
    "https://github.com/ZeusLN/zeus"
    "https://github.com/MutinyWallet/mutiny-web"
    "https://lnbits.com"
    "https://lnbits.com/shop"
    "https://btcpayserver.org/"
    "https://github.com/nostr-protocol/nips"
    "https://github.com/lnbits/lnbits"
    "https://github.com/lnbits/lnbits/tree/dev/docs/guide"
    "https://demo.lnbits.com/docs"
    "https://nostrapps.com"
    "https://github.com/sandwichfarm/nostr-geotags"
    "https://github.com/arbadacarbaYK/auction_house"
    "https://github.com/arbadacarbaYK/Pixelbot"
    "https://github.com/arbadacarbaYK/Tides"
    "https://github.com/arbadacarbaYK/nostr-zap-lamp"
    "https://plebtag.com/write"
    "https://lnurl-codec.netlify.app/"
    "https://docs.google.com/spreadsheets/d/147AXd8hN3uO3v_P1dupgfRCRzSMlH85dvQSHPAg7lZ4/edit?gid=981458315#gid=981458315"
    "https://github.com/breez"
    "https://github.com/slaninas/nostr-bot"
    "https://github.com/tokio-rs/tokio"
    "https://github.com/franzos/nostr-ts"
    "https://github.com/fiatjaf/nwak"
    "https://github.com/riccardobl/nostrduino"
    "https://github.com/nostr-dev-kit/ndk"
    "https://github.com/zkSNACKs/nostr-publish"
    "https://github.com/zkSNACKs"
    "https://github.com/cmdruid"
    "https://github.com/cmdruid/nostr-emitter"
    "https://github.com/PitilessPeanut/net_base"
    "https://github.com/getAlby/nostr-wallet-connect"
    "https://github.com/getAlby/bitcoin-connect"
    "https://github.com/benthecarman/nostr-wallet-connect-lnd"
    "https://github.com/horologger"
    "https://github.com/lnbits/nwcprovider"
    "https://github.com/hangwin/mcp-chrome"
    "https://github.com/lnbits"
    "https://github.com/lnbits/events"
    "https://docs.lnbits.org/devs/websockets.html"
    "https://docs.lnbits.org/devs/extensions.html"
    "https://docs.lnbits.org/guide/extension-install.html"
    "https://docs.lnbits.org/guide/funding-sources-table.html"
    "https://nips.nostr.com/"
    "https://github.com/hzrd149/blossom"
    "https://github.com/lnbits/boltcards"
    "https://github.com/DFXswiss"
    "https://github.com/Rsync25/awesome-bolt12"
    "https://github.com/Shubhamsaboo/awesome-llm-apps/blob/main/README.md"
    "https://github.com/trimstray/the-book-of-secret-knowledge"
    "https://tldr.sh/"
    "https://github.com/inovector/mixpost"
    "https://github.com/Azzamo-net/ban-api"
    "https://github.com/sbddesign/bip21-site"
    "https://github.com/rust-nostr/nostr"
    "https://azzamo.net/relays/"
    "https://ereignishorizont.xyz"
)

# Add each URL
for url in "${urls[@]}"; do
    echo "Adding: $url"
    curl -X POST http://localhost:3000/knowledge/add -H "Content-Type: application/json" -d "{\"url\": \"$url\"}" -s > /dev/null
    sleep 0.1  # Small delay to avoid overwhelming the server
done

echo "All URLs added successfully!"
echo "Now run: ./crawl_all.sh to crawl all the URLs with improved logic" 